start-emacs-server: Query emacs for socket directory.
General style and code cleanup.

diff --git a/em.in b/em.in
--- a/em.in
+++ b/em.in
@@ -44,7 +44,9 @@
 # If the environment variable SSH_TTY is set, and the ssh client and server
 # differ, then `--tty' command-line option is enabled by default.
 #
-shell_script=${0##*/}
+shopt -s extglob
+
+script_name=${0##*/}
 
 : ${AWK:='@AWK_CMD@'}
 : ${BASENAME:='@BASENAME_CMD@'}
@@ -69,9 +71,8 @@ shell_script=${0##*/}
 : ${TTY:='@TTY_CMD@'}
 : ${UNAME:='@UNAME_CMD@'}
 
-emacs_confdir="$HOME/.emacs.d"
+emacs_confdir="${HOME}/.emacs.d"
 emacs_server_log="${emacs_confdir}/emacs-server.log"
-emacs_socket_directory="${TMPDIR:-/tmp}"
 
 # Delay in seconds while buffer loads (system dependent).
 until_buffer_loads='0.5'
@@ -104,7 +105,7 @@ usage ()
 {
     $ED - <<EOF
 r !"$_EMACSCLIENT" --help
-1s;$_EMACSCLIENT;$shell_script;
+1s;$_EMACSCLIENT;$script_name;
 # Option \`-f' is shadowed by Emacs option \`--funcall'
 /-f SERVER, /s;;;
 .,+j
@@ -121,7 +122,7 @@ Extended options:
 --preload-files         Load FILEs in parallel, but visit one at a time.
 --save-kill             Save buffers and kill Emacs and Emacs server.
 --super-user            Visit FILEs with \`root' privileges via tramp.
---trace                 Trace execution of $shell_script(1) script.
+--trace                 Trace execution of $script_name(1) script.
 --two-way-merge=FILE1,FILE2[,OUTPUT-FILE]
                         Call \`emerge-files' with arguments FILE1 and FILE2.
                         Save output to OUTPUT-FILE if given.
@@ -161,13 +162,13 @@ EOF
 # Check shell interpreter version.
 interpreter-supported ()
 {
-    # $BASH_VERSION prerequisites (want: declare `-n' option)
+    # $BASH_VERSION prerequisites (want: declare option `-n')
     declare -i BASH_MAJOR_PREREQ=4
     declare -i BASH_MINOR_PREREQ=3
     declare -i BASH_REVISION_PREREQ=0
 
     if test ."$BASH_VERSION" = .''; then
-        echo "$shell_script: Bash shell required." >&2
+        echo "$script_name: Bash shell required." >&2
         return 1
     elif (( ${BASH_VERSINFO[0]} < BASH_MAJOR_PREREQ )) ||
              (( ${BASH_VERSINFO[0]} == BASH_MAJOR_PREREQ &&
@@ -175,7 +176,7 @@ interpreter-supported ()
              (( ${BASH_VERSINFO[0]} == BASH_MAJOR_PREREQ &&
                       ${BASH_VERSINFO[1]} == BASH_MINOR_PREREQ &&
                       ${BASH_VERSINFO[2]} < BASH_REVISION_PREREQ )); then
-        echo "$shell_script: $BASH_VERSION: Newer Bash shell required." >&2
+        echo "$script_name: $BASH_VERSION: Newer Bash shell required." >&2
         return 1
     fi
     return 0
@@ -194,7 +195,7 @@ environment-is-valid ()
 
     for var in ${envlist[*]} ; do
         if test ! -x "${!var}"; then
-            echo "$shell_script: ${!var}: Cannot exec" >&2
+            echo "$script_name: ${!var}: Cannot exec" >&2
             status+=1
         fi
     done
@@ -215,7 +216,7 @@ emacs-is-current ()
                 $AWK '{ print $NF }'
                   )
         if (( ${emacs_version%%.*} < EMACS_MAJOR_PREREQ )); then
-            echo "$shell_script: $emacs_version: Newer ${!var} required." >&2
+            echo "$script_name: $emacs_version: Newer ${!var} required." >&2
             status+=1
         fi
     done
@@ -244,18 +245,18 @@ create-frame-or-tty ()
 
 set-for-console ()
 {
-        # No frames, by default.
-        preload_files='false'
-        create_new_frames='false'
-        create_many_new_frames='false'
-        frame_or_tty='-nw'
+    # No frames, by default.
+    preload_files='false'
+    create_new_frames='false'
+    create_many_new_frames='false'
+    frame_or_tty='-nw'
 
-        # Provide default Emacs server name.  Overriden by option `-s'.
-        tty_name=$($TTY)
-        server_name="server$($ID -u)_${tty_name##*/}"
+    # Provide default Emacs server name.  Overriden by option `-s'.
+    tty_name=$($TTY)
+    server_name="server$($ID -u)_${tty_name##*/}"
 
-        # Run in foreground.
-        background_op=''
+    # Run in foreground.
+    background_op=''
 }
 
 # Set up environment for Emacs, as opposed to emacsclient.
@@ -272,7 +273,7 @@ raise-exception ()
 {
     error_status=$?
     echo "Exception raised in: $@" >&3
-    eval printf \"$shell_script: $error_diagnostic\\n\" >&3
+    eval printf \"$script_name: $error_diagnostic\\n\" >&3
     if test -s "$stderr_cache"; then
         printf "%s\n" "$(< "$stderr_cache" )" >&3
     fi
@@ -283,23 +284,34 @@ start-emacs-server ()
 {
     declare -i i=0
     declare first_diag='true'
+    declare server_socket_dir
+
+    server_socket_dir=$(
+        $_EMACS --batch -q  \
+                  --eval "(progn (server-start) (prin1 server-socket-dir))"
+                          )
+    if test ."$server_socket_dir" = .''; then
+        server_socket_dir=${TMPDIR:-'/tmp'}
+    fi
 
     echo -n "Launching Server... " >&3
 
-    # Removing any left-over sockets
-    $FIND "$emacs_socket_directory" -name emacs$($ID -u) -type d 2>/dev/null |
-        while read dir; do
-            if test -S "${dir}/${server_name}"; then
-                $RM -f "${dir}/${server_name}"
-            fi
-        done
+    # Removing any left-over socket
+    if test -d "$server_socket_dir"; then
+        $FIND "$server_socket_dir" -type s 2>/dev/null |
+            while read socket; do
+                if test ."${socket##*/}" = ."$server_name"; then
+                    $RM -f "$socket"
+                fi
+            done
+    fi
 
-    "$_EMACS" --daemon="${server_name}" >"$emacs_server_log" 2>&1 &
+    $_EMACS --daemon="$server_name" >"$emacs_server_log" 2>&1 &
     wait $! ||
         raise-exception 'server start'
 
     # Verify that server is accessible via emacsclient(1).
-    "$_EMACSCLIENT" -s "${server_name}" --no-wait --eval 't' >/dev/null ||
+    $_EMACSCLIENT -s "$server_name" --no-wait --eval 't' >/dev/null ||
         raise-exception 'server access'
 
     # Print Emacs startup errors/warnings to console.
@@ -652,7 +664,7 @@ option-requests ()
                 argv[argc++]+='"))'
 
                 # Emacs-specific argument, so invoke emacs(1).
-                _EMACSCLIENT="$_EMACS"
+                _EMACSCLIENT=$_EMACS
                 ;;
 
             # Extension option `--wait'
@@ -706,7 +718,7 @@ option-requests ()
                 fi
 
                 # Emacs-specific argument, so invoke Emacs.
-                _EMACSCLIENT="$_EMACS"
+                _EMACSCLIENT=$_EMACS
                 ;;
 
             # emacslcient options `-s' and `--socket-name'.
@@ -751,7 +763,7 @@ option-requests ()
                 shift
 
                 # Emacs-specific argument, so invoke Emacs.
-                _EMACSCLIENT="$_EMACS"
+                _EMACSCLIENT=$_EMACS
                 ;;
 
             # emacsclient option `--create-frame'.
@@ -775,7 +787,7 @@ option-requests ()
                 set -x
 
                 # Emacs-specific argument, so invoke Emacs.
-                _EMACSCLIENT="$_EMACS"
+                _EMACSCLIENT=$_EMACS
                 ;;
 
             # Emacs/emacsclient option `--eval'.
@@ -913,7 +925,7 @@ EOF
                 ;;
 
             +[0-9]*|-*)
-                argv[argc++]="$1"
+                argv[argc++]=$1
                 OPTIND+=1
                 shift
                 ;;
@@ -932,7 +944,7 @@ EOF
     if test ."$server_name" = .'' -a ."$_EMACSCLIENT" != ."$_EMACS"; then
         server_name="server$($ID -u)"
         argv[argc++]='-s'
-        argv[argc++]="$server_name"
+        argv[argc++]=$server_name
     fi
 }
 
@@ -943,7 +955,6 @@ fi
 
 # SSH session.
 if test ."$SSH_TTY" != .''; then
-
     declare -a endpoint=( $SSH_CONNECTION )
 
     # Client and server differ...
@@ -1071,7 +1082,7 @@ else
     fi
 
     # No file args...
-    if [[ $# == 0 ]]; then
+    if (( $# == 0 )); then
         eval '{
                 "$_EMACSCLIENT" $(create-frame-or-tty)                        \
                                 "${argv[@]}" ||
